<?php

use Illuminate\Database\Seeder;
use App\User;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Let's truncate our existing records to start from scratch.
        User::truncate();

        // API Token for testing. generated by str_random(60)
        $api_token = "2diF6syYbFkqb26EoFW5c3gvEVY1uRVOw4lEKmpIQxhcFY4qIPGE4aGjXJqP";

        // Creating a demo user in our database.
        User::create([
            'name' => "Gadi",
            'email' => "admin@pc.go.tz",
            'password' => bcrypt('123456'),
            'api_token' => $api_token
        ]);
    }
}
